const API_BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:5000";

export const API_URLS = {
  BASE_URL: API_BASE_URL,

  BLOG_LIST: `/api/blog`,
  BLOG_SEARCH: `/api/blog/search`,
  BLOG_CATEGORIES: `/api/blog/categories`,
  BLOG_POST: (slug: string) => `/api/blog/${slug}`,
  BLOG_CATEGORY: (category: string) => `/api/blog/category/${category}`,

  HTML_TO_PDF: `/api/pdf/html-to-pdf`,
  PDF_TO_IMAGE: `/api/pdf/to-image`,
  PDF_TO_WORD: `/api/pdf/to-word`,
  PDF_TO_EXCEL: `/api/pdf/to-excel`,
  PDF_TO_POWERPOINT: `/api/pdf/to-powerpoint`,
  WORD_TO_PDF: `/api/pdf/word-to-pdf`,
  POWERPOINT_TO_PDF: `/api/pdf/powerpoint-to-pdf`,
  PDF_MERGE: `/api/pdf/merge`,
  PDF_SPLIT: `/api/pdf/split`,
  PDF_PASSWORD: `/api/pdf/password`,
  PDF_UNLOCK: `/api/pdf/unlock`,
  PDF_PAGE_REMOVER: `/api/pdf/remove-pages`,
  PDF_ROTATE: `/api/pdf/rotate`,
  PDF_COMPRESS: `/api/pdf/compress`,

  IMAGE_COMPRESSOR: `/api/image/compress`,
  IMAGE_CONVERTER: `/api/image/convert`,
  IMAGE_RESIZE: `/api/image/resize`,
  IMAGE_CROP: `/api/image/crop`,
  BACKGROUND_REMOVER: `/api/image/ai-background-remover`,
  IMAGE_TO_PDF: `/api/image/image-to-pdf`,
  QR_GENERATOR: `/api/image/qr-generator`,
  QR_SCANNER: `/api/image/qr-scanner`,
  IMAGE_BASE64: `/api/image/base64`,
  EXIF_VIEWER: `/api/image/exif-viewer`,
  FAVICON_GENERATOR: `/api/image/favicon-generator`,
  IMAGE_DPI_CHECKER: `/api/image/dpi-checker`,

  AUDIO_CONVERTER: `/api/audio/convert`,
  AUDIO_MERGER: `/api/audio/merge`,
  AUDIO_TRIMMER: `/api/audio/trim`,
  AUDIO_SPEED: `/api/audio/speed`,
  SPEECH_TO_TEXT: `/api/audio/ai-speech-to-text`,

  VIDEO_TO_AUDIO: `/api/video/video-to-audio`,
  VIDEO_TRIM: `/api/video/trim`,
  VIDEO_SPEED: `/api/video/speed`,
  VIDEO_THUMBNAIL: `/api/video/thumbnail`,
  VIDEO_RESOLUTION: `/api/video/resolution`,

  PASSWORD_GENERATOR: `/api/security/password-generator`,
  PASSWORD_STRENGTH: `/api/security/password-strength`,
  HASH_GENERATOR: `/api/security/hash-generator`,
  BASE64_ENCODER: `/api/security/base64`,
  UUID_GENERATOR: `/api/security/uuid-generator`,
  PASSWORD_STRENGTH_EXPLAINER: `/api/security/ai-password-strength-explainer`,
  DATA_BREACH_EMAIL_CHECKER: `/api/security/data-breach-checker`,
  FILE_HASH_COMPARISON: `/api/security/file-hash-comparison`,
  EXIF_LOCATION_REMOVER: `/api/security/exif-location-remover`,
  TEXT_REDACTION: `/api/security/ai-text-redaction`,
  QR_PHISHING_SCANNER: `/api/security/ai-qr-phishing-scanner`,
  SECURE_NOTES: `/api/security/secure-notes`,
  URL_REPUTATION_CHECKER: `/api/security/ai-url-reputation-checker`,

  DATE_DIFFERENCE: `/api/date-time/date-difference`,
  WORKING_DAYS: `/api/date-time/working-days`,
  COUNTDOWN_TIMER: `/api/date-time/countdown`,
  WORLD_TIME: `/api/date-time/world-time`,
  AGE_CALCULATOR: `/api/date-time/age-calculator`,

  JSON_FORMATTER: `/api/dev/json-formatter`,
  URL_ENCODER: `/api/dev/url-encoder`,
  COLOR_CONVERTER: `/api/dev/color-converter`,
  LOREM_GENERATOR: `/api/dev/lorem-generator`,
  JWT_DECODER: `/api/dev/jwt-decoder`,
  CRON_GENERATOR: `/api/dev/ai-cron-generator`,
  UUID_GENERATOR_DEV: `/api/dev/uuid-generator`,
  HTTP_HEADER_CHECKER: `/api/dev/http-header-checker`,
  JSON_TO_TYPESCRIPT: `/api/dev/ai-json-to-typescript-interface`,
  SQL_QUERY_BEAUTIFIER: `/api/dev/ai-sql-query-beautifier`,
  DOCKERFILE_GENERATOR: `/api/dev/ai-dockerfile-generator`,
  CURL_TO_AXIOS: `/api/dev/curl-to-axios`,
  HTTP_STATUS_CODE: `/api/dev/http-status-codes`,

  UNIT_CONVERTER: `/api/education/unit-converter`,
  SIMPLE_INTEREST: `/api/education/simple-interest`,
  CGPA_TO_PERCENTAGE: `/api/education/cgpa-to-percentage`,
  LCM_HCF: `/api/education/lcm-hcf`,

  EMI_CALCULATOR: `/api/finance/emi-calculator`,
  GST_CALCULATOR: `/api/finance/gst-calculator`,
  SALARY_CALCULATOR: `/api/finance/salary-calculator`,
  CURRENCY_CONVERTER: `/api/finance/currency-converter`,
  STARTUP_BURN_RATE: `/api/finance/burn-rate-calculator`,
  SAAS_PRICING: `/api/finance/ai-saas-pricing-calculator`,
  EMI_COMPARISON: `/api/finance/emi-comparison`,
  TAX_SLAB_ANALYZER: `/api/finance/ai-tax-slab-analyzer`,
  INVOICE_GENERATOR: `/api/finance/invoice-generator`,
  PROFIT_MARGIN: `/api/finance/profit-margin`,
  FREELANCER_RATE: `/api/finance/freelancer-rate-calculator`,
  SALARY_BREAKUP: `/api/finance/salary-breakup-generator`,
  BUDGET_PLANNER: `/api/finance/ai-budget-planner`,
  STOCK_CAGR: `/api/finance/stock-cagr-calculator`,

  IP_LOOKUP: `/api/internet/ip-lookup`,
  USER_AGENT: `/api/internet/user-agent`,
  DNS_LOOKUP: `/api/internet/dns-lookup`,
  SSL_CHECKER: `/api/internet/ssl-checker`,
  WEBSITE_PING: `/api/internet/website-ping`,
  PING_TEST: `/api/internet/website-ping`,
  WEBSITE_SCREENSHOT: `/api/internet/website-screenshot`,

  META_TITLE_DESCRIPTION: `/api/seo/meta-title-description`,
  KEYWORD_DENSITY: `/api/seo/keyword-density-checker`,
  ROBOTS_TXT: `/api/seo/robots-txt-generator`,
  SITEMAP_VALIDATOR: `/api/seo/sitemap-validator`,
  OG_IMAGE_PREVIEW: `/api/seo/og-image-preview`,
  BROKEN_IMAGE_FINDER: `/api/seo/broken-image-finder`,
  UTM_LINK_BUILDER: `/api/seo/utm-link-builder`,
  DOMAIN_AGE: `/api/seo/domain-age-checker`,
  TECH_STACK_DETECTOR: `/api/seo/ai-tech-stack-detector`,

  HASHTAG_GENERATOR: `/api/social/ai-hashtag-generator`,
  BIO_GENERATOR: `/api/social/ai-bio-generator`,
  CAPTION_FORMATTER: `/api/social/caption-formatter`,
  LINE_BREAK_GENERATOR: `/api/social/line-break-generator`,

  WORD_COUNTER: `/api/text/word-counter`,
  CASE_CONVERTER: `/api/text/case-converter`,
  MARKDOWN_HTML: `/api/text/markdown-to-html`,
  REMOVE_SPACES: `/api/text/remove-spaces`,
  LINE_SORTER: `/api/text/line-sorter`,
  DUPLICATE_REMOVER: `/api/text/duplicate-remover`,
  TEXT_SUMMARIZER: `/api/text/ai-text-summarizer`,
  TEXT_DIFF: `/api/text/text-diff`,

  CREATE_ZIP: `/api/zip/create`,
  EXTRACT_ZIP: `/api/zip/extract`,
  PASSWORD_ZIP: `/api/zip/password`,
  COMPRESSION_ZIP: `/api/zip/compression-test`,

  EMAIL_SUBJECT_LINE: `/api/email/ai-subject-line-generator`,
  EMAIL_SIGNATURE: `/api/email/ai-signature-generator`,
  HTML_EMAIL_PREVIEWER: `/api/email/previewer-analyze`,
  SPAM_SCORE_CHECKER: `/api/email/ai-spam-checker`,
  EMAIL_TEMPLATE_BUILDER: `/api/email/ai-template-builder`,
  EMAIL_HEADER_ANALYZER: `/api/email/ai-header-analyzer`,
  SPF_RECORD_GENERATOR: `/api/email/spf-generator`,
  DKIM_GENERATOR: `/api/email/dkim-generator`,
  DMARC_GENERATOR: `/api/email/dmarc-generator`,
  MAILTO_LINK_GENERATOR: `/api/email/mailto-generator`,

  // ==========================================
  // Client-Side Only Tools (No Server Requests)
  // ==========================================
  // These tools perform all operations locally inside the browser.
  // The endpoints below are placeholders for schema structure and self-checks.
  REGEX_TESTER: `/api/dev/regex-tester`,
  API_RESPONSE_FORMATTER: `/api/dev/api-response-formatter`,
  JWT_EXPIRY: `/api/dev/jwt-expiry`,
  ENVIRONMENT_VARIABLE: `/api/dev/environment-variable`,
  POSTMAN_COLLECTION: `/api/dev/ai-postman-collection`,
  SCIENTIFIC_CALCULATOR: `/api/education/scientific-calculator`,
  PERCENTAGE_CALCULATOR: `/api/education/percentage-calculator`,
  COMPOUND_INTEREST: `/api/education/compound-interest`,
  STUDY_TIMETABLE: `/api/education/ai-study-timetable`,
  MCQ_GENERATOR: `/api/education/ai-mcq-generator`,
  HTTP_STATUS: `/api/internet/http-status`,
  PAGE_SPEED_CHECKLIST: `/api/seo/page-speed-checklist`,
  PAGE_SEO: `/api/seo/ai-page-seo-analyzer`,
  LINK_IN_BIO: `/api/social/link-in-bio`,
  MEME_GENERATOR: `/api/social/ai-meme-generator`,
  DOCUMENT_TEMPLATE: `/api/govt-legal/document-template`,
  PDF_COMPRESSOR_GOV: `/api/govt-legal/pdf-compressor`,
  PASSPORT_PHOTO_RESIZER: `/api/govt-legal/passport-photo-resizer`,
  SIGNATURE_MAKER: `/api/govt-legal/signature-maker`,
  BARCODE_GENERATOR: `/api/ecommerce/barcode-generator`,
  BULK_IMAGE_RESIZER: `/api/ecommerce/bulk-image-resizer`,
  ECOMMERCE_CALCULATOR: `/api/ecommerce/calculator`,
  GST_INVOICE_GENERATOR: `/api/ecommerce/gst-invoice-generator`,
  IMAGE_COLOR_ENHANCER: `/api/ecommerce/ai-image-color-enhancer`,
  SHADOW_ADDER: `/api/ecommerce/ai-shadow-adder`,
  WATERMARK_ADDER: `/api/ecommerce/watermark-adder`,
  WHITE_BACKGROUND_ADDER: `/api/ecommerce/white-background-adder`,
  SPLIT_ZIP: `/api/zip/split`,
  MERGE_ZIP: `/api/zip/merge`,
};

export default API_BASE_URL;
